apiVersion: v1
kind: Namespace
metadata:
  name: secrets-tutorial

---

apiVersion: v1
kind: Secret
metadata:
  name: my-first-secret
  namespace: secrets-tutorial
stringData:
  SECRET_CONFIG: |  # this is the name of the file injected in the Pods
    username: marco
    password: P@s$w0rD5935

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secrets-sample-deploy
  namespace: secrets-tutorial
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secrets-sample
  template:
    metadata:
      labels:
        app: secrets-sample
    spec:
      containers:
        - name: secrets-sample
          image: alpine:latest
          command: ["sleep", "3600"]
          volumeMounts:
            - mountPath: "/config/secrets/"
              name: secret-config-volume
              readOnly: true
          env:
            - name: CREDENTIALS
              valueFrom:
                secretKeyRef:
                  key: SECRET_CONFIG
                  name: my-first-secret
          envFrom:
            - secretRef:
                name: my-first-secret
      volumes:
        - name: secret-config-volume
          secret:
            secretName: my-first-secret
