
apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
  labels:
    app: queue
spec:
  selector:
    app: queue
  ports:
    - name: http
      port: 8161
      nodePort: 30100
    - name: endpoint
      port: 61616
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
  labels:
    app: position-tracker
spec:
  selector:
    app: position-tracker
  ports:
    - name: http
      port: 8080
      nodePort: 30020
  type: NodePort
  # type: ClusterIp  # use this to expose only to the cluster

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway
  labels:
    app: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - name: http
      port: 8080
      nodePort: 30030
  type: NodePort
  # type: ClusterIp  # use this to expose only to the cluster

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
  labels:
    app: webapp
spec:
  selector:
    app: webapp
  ports:
    - name: http
      port: 80
      nodePort: 30080
  type: NodePort
  # type: ClusterIP  # use this to expose only to the cluster

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-mongodb
  labels:
    app: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - name: mongo-port
      port: 27017
  type: ClusterIP

---
