bases:
  - ../../base/
patches:
  - ./replica_count.yaml
configMapGenerator:
  - name: kustomize-example-cfgmap
    namespace: kustomize-example
    # behavior: replace  # cm managed by kustomize
    files:
      - ./configs/config.json
images:
  - name: "aimvector/python"
    newTag: 1.0.1
