apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: "standard"
  capacity:
    storage: 5Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    # this assumes a folder in your local filesystem with an index.html file in it
    path: "/k8s-data/"  

---
## PV Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
---
# Pod
apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
  labels: 
    app: pv-sample
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
  containers:
    - name: task-pv-container
      image: httpd:alpine
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/local/apache2/htdocs/"
          name: task-pv-storage
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: pv-sample-app
spec:
  selector:
    app: pv-sample
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: NodePort
---
# Ingress rules
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /   #new 
  name: pv-sample-app
  namespace: default
spec:
  tls:
  - hosts:
    - localhost
  rules:
  - host: localhost
    http:
      paths:
      - path: /pv-claim
        backend:
          serviceName: pv-sample-app
          servicePort: 80
