name: build-sphinx-to-gh-pages

env:
  GITHUB_ACTOR: calcifer777
  GITHUB_REPOSITORY: calcifer777/learn-kubernetes
  GITHUB_TOKEN: ${{ secrets.CREATE_DEMO_SECRET }}

on: 
  push:
    branches: [ master ]

jobs:
  build:
    name: Sphinx Pages Test
    runs-on: ubuntu-latest
    steps:
      - uses: seanzhengw/sphinx-pages@master
        id: sphinx-pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          create_readme: true
